version: "2"
run:
  timeout: 5m
  tests: true

linters:
  default: all
  disable:
    - depguard
    - wrapcheck
    - revive
    - mnd
    - godot
    - forcetypeassert
    - err113
    - exhaustruct
    - funcorder
    - paralleltest
    - perfsprint
    - varnamelen
    - testifylint
    - funlen
    - testpackage
    - tagalign
    - errcheck
    - gosec
    - gochecknoglobals
    - ireturn


  settings:
    misspell: { locale: US }

formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sljivkov/dectek)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
